MONGODB_HOST: mongodb-{{ env }}.ashokking.sbs  #mongodb-dev-ashokking.sbs
REDIS_HOST: redis-{{ env }}.ashokking.sbs
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.ashokking.sbs
CART_HOST: cart.backend-alb-{{ env }}.ashokking.sbs
USER_HOST: user.backend-alb-{{ env }}.ashokking.sbs
RABBITMQ_HOST: rabbitmq-{{ env }}.ashokking.sbs
MYSQL_HOST: mysql-{{ env }}.ashokking.sbs
SHIPPING_HOST: shipping.backend-alb-{{ env }}.ashokking.sbs
PAYMENT_HOST: payment.backend-alb-{{ env }}.ashokking.sbs